### ISSUE TITLE
主动让光标失去焦点，然后直接插入表情包是不能插入的

### ISSUE THREAD

**Issue by Tabxx** [ylfeng250/div-editor#1]
主动让光标失去焦点，然后直接插入表情包是不能插入的

**Comment by storagess** [comment]
@Tabxx   嗯嗯，表情基本解决了。我想问你个问题。一张图片然后有文字，假如我复制了一段文字，如何在这个图片的光标后面插入文本呢。然后光标也正确

**Comment by ylfeng250** [comment]
> 主动让光标失去焦点，然后直接插入表情包是不能插入的

谢谢反馈。
